CREATE TABLE seller_orders_sellerorder(
    created_at TIMESTAMP NOT NULL,
	updated_at TIMESTAMP NOT NULL,
	id BINARY(16) NOT NULL,
	code varchar(16) NOT NULL,
	order_id BINARY(16) NOT NULL,
	channel_slug varchar(16) NOT NULL,
	channel_store varchar(100) NOT NULL,
	seller_id BINARY(16) NOT NULL,
	seller_name varchar(100) NOT NULL,
	purchase_timestamp TIMESTAMP NOT NULL,
	status varchar(20) NOT NULL,
	approved_at TIMESTAMP NOT NULL,
	shipping_limit_date TIMESTAMP NOT NULL,
	availability_days int4 NOT NULL,
	invoice_url varchar(200) NOT NULL,
	invoice_issue_date TIMESTAMP NULL,
	invoice_key varchar(100) NOT NULL,
	invoice_number int4 NOT NULL,
	invoice_serial_number int4 NOT NULL,
	customer_id BINARY(16) NOT NULL,
	shipment_id BINARY(16) NULL,
	invoice_source varchar(32) NOT NULL,
	delivered_customer_date TIMESTAMP NULL,
	seller_brand varchar(256) NOT NULL,
	seller_email varchar(254) NOT NULL,
	invoice_danfe_url varchar(200) NOT NULL,
	cancelation_reason varchar(64) NOT NULL,
	cancelation_status varchar(64) NOT NULL,
	suspension_reason varchar(64) NOT NULL,
	estimated_delivery_date date NULL,
	invoice_status varchar(16) NOT NULL,
	invoice_id BINARY(16) NULL,
	branded_store_slug varchar(32) NOT NULL,
	search_vector text,
	shipping_quote_group_id BINARY(16) NULL,
	payer_id BINARY(16),
	display_status varchar(20) NOT NULL,
	estimated_delivery_shift varchar(16) NOT NULL,
	invoice_errors json NULL
);
